---
title: Facial recognition
hero_image: images/banner.png
description: 
version: 4
listed: false
copyedit: true
last_tested: '2018-12-06'
steps:
- title: Introduction
- title: Build a Classify function
- title: Use your own photos, with a camera
  completion:
  - engaged
- title: Use your own photos, without a camera
- title: Build an interface
  completion:
  - internal
