title: c3-wolfram-facial-recognition
hero_image: images/banner.png
description: c3-wolfram-facial-recognition description
version: 4
listed: false
copyedit: false
last_tested: "2019-01-30"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
