title: Harry Potter and the Facial Recognition Classifier
hero_image: images/banner.png
description:
version: 4
listed: false
copyedit: false
last_tested: "2018-12-06"
steps:
  - title: Introduction
  - title: Build a Classify function
  - title: Use your own photos, with a camera
  - title: Use your own photos, without a camera
  - title: Build an interface
