title: Harry Potter and the Facial Recognition Classifier
hero_image: images/banner.png
description:
version: 4
listed: false
copyedit: false
last_tested: "2018-12-06"
steps:
  - title: Introduction
  - title: Building a Classify Function
  - title: Using Your Own Photos, With a Camera
  - title: Using Your Own Photos, Without a Camera
  - title: Building an Interface
